subjects = {'dlsubj003',...
            'dlsubj123',...
            'dlsubj127',...
            'dlsubj128',...
            'dlsubjDR',...
            'dlsubjEV',...
            'dlsubjJG',...
            'dlsubjLA',...
            'dlsubjLR',... 
            'dlsubjLS',...
            };

NP_prfPropertiesCompare(subjects);